#!/bin/sh

# Add RPMForge
rpm -Uvh http://apt.sw.be/redhat/el5/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.2-2.el5.rf.x86_64.rpm
yum install -y git make

git clone http://github.com/tarate/postfixcfg.git
